name: teachopencadd
channels:
  - conda-forge
  - defaults
  - samoturk
dependencies:
  - python
  - jupyter
  - rdkit
  - pmw
  - scikit-learn
  - biopandas
  - seaborn
  - pypdb
  - chembl_webresource_client
  - nglview
  - pytest-notebook